<?php

namespace Database\Seeders;

use App\Models\BadgeDefinition;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    public function run(): void
    {
        $badges = [
            // === Onboarding (unique) ===
            [
                'code' => 'premier_bien',
                'category' => 'onboarding',
                'name' => 'Premier bien',
                'description' => 'Vous avez enregistré votre premier bien immobilier. La base de votre comptabilité LMNP est posée.',
                'hint' => 'Créez votre premier bien dans Mes biens → Biens immobiliers → Nouveau.',
                'icon' => 'heroicon-o-home-modern',
                'color' => 'primary',
                'is_yearly' => false,
                'sort_order' => 1,
                'unlock_conditions' => ['type' => 'property_count', 'min' => 1],
            ],
            [
                'code' => 'architecte',
                'category' => 'onboarding',
                'name' => 'Architecte',
                'description' => 'Composants d\'amortissement configurés. Vos dotations seront calculées correctement.',
                'hint' => 'Ajoutez au moins 5 composants d\'amortissement à un bien (gros œuvre, toiture, etc.).',
                'icon' => 'heroicon-o-building-library',
                'color' => 'primary',
                'is_yearly' => false,
                'sort_order' => 2,
                'unlock_conditions' => ['type' => 'component_count', 'min' => 5],
            ],
            [
                'code' => 'importateur',
                'category' => 'onboarding',
                'name' => 'Importateur',
                'description' => 'Premier import CSV réussi. L\'automatisation réduit les erreurs de saisie.',
                'hint' => 'Importez un fichier CSV Airbnb via Import Airbnb ou l\'assistant annuel.',
                'icon' => 'heroicon-o-arrow-down-tray',
                'color' => 'primary',
                'is_yearly' => false,
                'sort_order' => 3,
                'unlock_conditions' => ['type' => 'csv_imported'],
            ],
            [
                'code' => 'banquier',
                'category' => 'onboarding',
                'name' => 'Banquier',
                'description' => 'Prêt immobilier enregistré. Les intérêts d\'emprunt seront déduits automatiquement.',
                'hint' => 'Créez un prêt dans Financement → Prêts → Nouveau.',
                'icon' => 'heroicon-o-building-office-2',
                'color' => 'primary',
                'is_yearly' => false,
                'sort_order' => 4,
                'unlock_conditions' => ['type' => 'loan_count', 'min' => 1],
            ],
            [
                'code' => 'premiere_annee',
                'category' => 'onboarding',
                'name' => 'Première année',
                'description' => 'Premier exercice fiscal créé. Votre suivi comptable annuel a commencé.',
                'hint' => 'Créez un exercice fiscal via Fiscal → Exercices fiscaux ou l\'assistant de clôture.',
                'icon' => 'heroicon-o-calendar',
                'color' => 'primary',
                'is_yearly' => false,
                'sort_order' => 5,
                'unlock_conditions' => ['type' => 'fiscal_year_count', 'min' => 1],
            ],

            // === Régularité (annuel) ===
            [
                'code' => 'mois_complet',
                'category' => 'regularite',
                'name' => 'Mois complet',
                'description' => 'Au moins un mois avec recettes et charges saisies. La régularité évite l\'oubli de pièces.',
                'hint' => 'Saisissez au moins une recette ET une charge sur le même mois calendaire.',
                'icon' => 'heroicon-o-check-circle',
                'color' => 'success',
                'is_yearly' => true,
                'sort_order' => 10,
                'unlock_conditions' => ['type' => 'complete_months', 'min' => 1],
            ],
            [
                'code' => 'trimestre_ok',
                'category' => 'regularite',
                'name' => 'Trimestre impeccable',
                'description' => '3 mois consécutifs complets. Votre comptabilité est tenue régulièrement.',
                'hint' => 'Complétez 3 mois consécutifs avec des recettes et charges saisies chaque mois.',
                'icon' => 'heroicon-o-calendar-days',
                'color' => 'success',
                'is_yearly' => true,
                'sort_order' => 11,
                'unlock_conditions' => ['type' => 'consecutive_months', 'min' => 3],
            ],
            [
                'code' => 'semestre_ok',
                'category' => 'regularite',
                'name' => 'Semestre régulier',
                'description' => '6 mois consécutifs complets. La moitié de l\'année est comptabilisée sans interruption.',
                'hint' => 'Complétez 6 mois consécutifs avec des recettes et charges saisies chaque mois.',
                'icon' => 'heroicon-o-clock',
                'color' => 'success',
                'is_yearly' => true,
                'sort_order' => 12,
                'unlock_conditions' => ['type' => 'consecutive_months', 'min' => 6],
            ],
            [
                'code' => 'annee_complete',
                'category' => 'regularite',
                'name' => 'Année complète',
                'description' => '12 mois avec données saisies. Votre exercice est complet, prêt pour la clôture.',
                'hint' => 'Saisissez des recettes et charges pour chacun des 12 mois de l\'année.',
                'icon' => 'heroicon-o-star',
                'color' => 'warning',
                'is_yearly' => true,
                'sort_order' => 13,
                'unlock_conditions' => ['type' => 'complete_months', 'min' => 12],
            ],
            [
                'code' => 'rapide',
                'category' => 'regularite',
                'name' => 'Déclarant rapide',
                'description' => 'Exercice clôturé avant le 1er avril. Vous êtes en avance sur le calendrier fiscal.',
                'hint' => 'Clôturez votre exercice fiscal avant le 1er avril de l\'année suivante.',
                'icon' => 'heroicon-o-bolt',
                'color' => 'warning',
                'is_yearly' => true,
                'sort_order' => 14,
                'unlock_conditions' => ['type' => 'closed_before_date', 'month' => 4, 'day' => 1],
            ],

            // === Qualité (annuel) ===
            [
                'code' => 'rigoureux',
                'category' => 'qualite',
                'name' => 'Rigoureux',
                'description' => '100% des charges ont un justificatif. Vous êtes prêt en cas de contrôle fiscal.',
                'hint' => 'Attachez un justificatif (PDF, photo) à chacune de vos charges de l\'exercice.',
                'icon' => 'heroicon-o-document-check',
                'color' => 'info',
                'is_yearly' => true,
                'sort_order' => 20,
                'unlock_conditions' => ['type' => 'receipt_coverage', 'min_percent' => 100],
            ],
            [
                'code' => 'categorise',
                'category' => 'qualite',
                'name' => 'Bien catégorisé',
                'description' => 'Aucune charge en catégorie « Autre ». Toutes vos dépenses sont correctement classées.',
                'hint' => 'Classez toutes vos charges dans une catégorie précise (pas « Divers »).',
                'icon' => 'heroicon-o-tag',
                'color' => 'info',
                'is_yearly' => true,
                'sort_order' => 21,
                'unlock_conditions' => ['type' => 'no_other_category'],
            ],
            [
                'code' => 'fec_conforme',
                'category' => 'qualite',
                'name' => 'FEC conforme',
                'description' => 'Fichier des Écritures Comptables généré sans erreur. Conforme aux exigences fiscales.',
                'hint' => 'Générez le FEC depuis Fiscal → Exercices fiscaux → bouton « FEC ».',
                'icon' => 'heroicon-o-shield-check',
                'color' => 'info',
                'is_yearly' => true,
                'sort_order' => 22,
                'unlock_conditions' => ['type' => 'fec_generated'],
            ],
            [
                'code' => 'liasse_ok',
                'category' => 'qualite',
                'name' => 'Liasse fiscale',
                'description' => 'Liasse fiscale PDF générée. Votre déclaration est prête pour la transmission.',
                'hint' => 'Générez la liasse PDF depuis Fiscal → Exercices fiscaux → bouton « PDF ».',
                'icon' => 'heroicon-o-document-text',
                'color' => 'info',
                'is_yearly' => true,
                'sort_order' => 23,
                'unlock_conditions' => ['type' => 'tax_return_generated'],
            ],
            [
                'code' => 'reconcilie',
                'category' => 'qualite',
                'name' => 'Réconcilié',
                'description' => 'Toutes les recettes proviennent d\'un import CSV. Cohérence entre plateforme et comptabilité.',
                'hint' => 'Importez toutes vos recettes via CSV Airbnb au lieu de les saisir manuellement.',
                'icon' => 'heroicon-o-check-badge',
                'color' => 'info',
                'is_yearly' => true,
                'sort_order' => 24,
                'unlock_conditions' => ['type' => 'all_incomes_imported'],
            ],

            // === Exploration (unique) ===
            [
                'code' => 'simulateur',
                'category' => 'exploration',
                'name' => 'Analyste fiscal',
                'description' => 'Simulateur micro-BIC vs réel utilisé. Vous avez comparé les deux régimes.',
                'hint' => 'Consultez la page Fiscal → Simulateur pour comparer micro-BIC et régime réel.',
                'icon' => 'heroicon-o-calculator',
                'color' => 'danger',
                'is_yearly' => false,
                'sort_order' => 30,
                'unlock_conditions' => ['type' => 'simulator_used'],
            ],
            [
                'code' => 'prospecteur',
                'category' => 'exploration',
                'name' => 'Prospecteur',
                'description' => 'Projection financière lancée. Vous anticipez l\'évolution de votre investissement.',
                'hint' => 'Consultez la page Fiscal → Projection pour voir l\'évolution sur plusieurs années.',
                'icon' => 'heroicon-o-chart-bar',
                'color' => 'danger',
                'is_yearly' => false,
                'sort_order' => 31,
                'unlock_conditions' => ['type' => 'projection_used'],
            ],
            [
                'code' => 'optimiseur',
                'category' => 'exploration',
                'name' => 'Optimiseur',
                'description' => 'Report d\'amortissement excédentaire constaté. Vous optimisez votre fiscalité dans le temps.',
                'hint' => 'Créez un exercice fiscal où les amortissements dépassent le résultat avant amortissement.',
                'icon' => 'heroicon-o-arrow-trending-up',
                'color' => 'danger',
                'is_yearly' => false,
                'sort_order' => 32,
                'unlock_conditions' => ['type' => 'deferred_depreciation'],
            ],
            [
                'code' => 'multi_biens',
                'category' => 'exploration',
                'name' => 'Multi-propriétaire',
                'description' => 'Deux biens ou plus en gestion. Votre portefeuille immobilier se développe.',
                'hint' => 'Ajoutez un deuxième bien immobilier dans Mes biens → Nouveau.',
                'icon' => 'heroicon-o-squares-2x2',
                'color' => 'danger',
                'is_yearly' => false,
                'sort_order' => 33,
                'unlock_conditions' => ['type' => 'property_count', 'min' => 2],
            ],
            [
                'code' => 'veteran',
                'category' => 'exploration',
                'name' => 'Vétéran LMNP',
                'description' => '3 exercices fiscaux clôturés. Vous maîtrisez votre comptabilité LMNP.',
                'hint' => 'Clôturez 3 exercices fiscaux différents (le temps fait le reste).',
                'icon' => 'heroicon-o-trophy',
                'color' => 'warning',
                'is_yearly' => false,
                'sort_order' => 34,
                'unlock_conditions' => ['type' => 'closed_fiscal_years', 'min' => 3],
            ],
        ];

        foreach ($badges as $badge) {
            BadgeDefinition::updateOrCreate(
                ['code' => $badge['code']],
                $badge,
            );
        }
    }
}
